-- Migration 157: HIPAA Security Rule implementation specifications
--
-- The hipaa framework listed the 22 Security Rule standards but none of the
-- implementation specifications under them, so a covered entity could not
-- show which Required specifications were met or document its decisions on
-- the Addressable ones, which is what OCR asks for in an investigation.
-- This migration adds the 40 implementation specifications of 45 CFR
-- 164.308-164.314 as child controls of their standard (parent_control_id),
-- each titled Required or Addressable, and the missing 164.308(b)(1)
-- business associate standard. Text follows the regulation.
--
-- Idempotent: rows are matched on (framework_id, control_id); existing rows
-- keep their id so implementations and evidence links are untouched.

DO $$
DECLARE
  fw_id UUID;
BEGIN
  SELECT id INTO fw_id FROM frameworks WHERE code = 'hipaa';
  IF fw_id IS NULL THEN
    RAISE NOTICE 'hipaa framework not present; skipping implementation specifications';
    RETURN;
  END IF;

  INSERT INTO framework_controls (framework_id, control_id, title, description, control_type, priority)
  VALUES (fw_id, 'HIPAA-164.308(b)(1)', 'Business Associate Contracts and Other Arrangements',
          $cw$A covered entity may permit a business associate to create, receive, maintain, or transmit electronic protected health information on its behalf only if it obtains satisfactory assurances that the business associate will appropriately safeguard the information. A business associate must obtain the same assurances from its subcontractors.$cw$,
          'organizational', '1')
  ON CONFLICT (framework_id, control_id) DO NOTHING;

  UPDATE framework_controls
     SET title = 'Documentation: Time Limit, Availability, Updates (Required)'
   WHERE framework_id = fw_id AND control_id = 'HIPAA-164.316(b)(2)';

  INSERT INTO framework_controls (framework_id, control_id, title, description, control_type, priority, parent_control_id, is_enhancement)
  SELECT fw_id, spec.control_id, spec.title, spec.description, spec.control_type, spec.priority, parent.id, true
    FROM (VALUES
      ('HIPAA-164.308(a)(1)', 'HIPAA-164.308(a)(1)(ii)(A)', $cw$Risk Analysis (Required)$cw$, $cw$Conduct an accurate and thorough assessment of the potential risks and vulnerabilities to the confidentiality, integrity, and availability of electronic protected health information held by the covered entity or business associate.$cw$, 'strategic', '1'),
      ('HIPAA-164.308(a)(1)', 'HIPAA-164.308(a)(1)(ii)(B)', $cw$Risk Management (Required)$cw$, $cw$Implement security measures sufficient to reduce risks and vulnerabilities to a reasonable and appropriate level to comply with 164.306(a).$cw$, 'strategic', '1'),
      ('HIPAA-164.308(a)(1)', 'HIPAA-164.308(a)(1)(ii)(C)', $cw$Sanction Policy (Required)$cw$, $cw$Apply appropriate sanctions against workforce members who fail to comply with the security policies and procedures of the covered entity or business associate.$cw$, 'organizational', '1'),
      ('HIPAA-164.308(a)(1)', 'HIPAA-164.308(a)(1)(ii)(D)', $cw$Information System Activity Review (Required)$cw$, $cw$Implement procedures to regularly review records of information system activity, such as audit logs, access reports, and security incident tracking reports.$cw$, 'technical', '1'),
      ('HIPAA-164.308(a)(3)', 'HIPAA-164.308(a)(3)(ii)(A)', $cw$Authorization and/or Supervision (Addressable)$cw$, $cw$Implement procedures for the authorization and/or supervision of workforce members who work with electronic protected health information or in locations where it might be accessed. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'organizational', '2'),
      ('HIPAA-164.308(a)(3)', 'HIPAA-164.308(a)(3)(ii)(B)', $cw$Workforce Clearance Procedure (Addressable)$cw$, $cw$Implement procedures to determine that the access of a workforce member to electronic protected health information is appropriate. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'organizational', '2'),
      ('HIPAA-164.308(a)(3)', 'HIPAA-164.308(a)(3)(ii)(C)', $cw$Termination Procedures (Addressable)$cw$, $cw$Implement procedures for terminating access to electronic protected health information when the employment of, or other arrangement with, a workforce member ends or as required by determinations made under the workforce clearance procedure. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'organizational', '2'),
      ('HIPAA-164.308(a)(4)', 'HIPAA-164.308(a)(4)(ii)(A)', $cw$Isolating Health Care Clearinghouse Functions (Required)$cw$, $cw$If a health care clearinghouse is part of a larger organization, the clearinghouse must implement policies and procedures that protect the electronic protected health information of the clearinghouse from unauthorized access by the larger organization.$cw$, 'technical', '1'),
      ('HIPAA-164.308(a)(4)', 'HIPAA-164.308(a)(4)(ii)(B)', $cw$Access Authorization (Addressable)$cw$, $cw$Implement policies and procedures for granting access to electronic protected health information, for example, through access to a workstation, transaction, program, process, or other mechanism. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.308(a)(4)', 'HIPAA-164.308(a)(4)(ii)(C)', $cw$Access Establishment and Modification (Addressable)$cw$, $cw$Implement policies and procedures that, based upon the access authorization policies, establish, document, review, and modify a user’s right of access to a workstation, transaction, program, or process. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.308(a)(5)', 'HIPAA-164.308(a)(5)(ii)(A)', $cw$Security Reminders (Addressable)$cw$, $cw$Periodic security updates. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'organizational', '2'),
      ('HIPAA-164.308(a)(5)', 'HIPAA-164.308(a)(5)(ii)(B)', $cw$Protection from Malicious Software (Addressable)$cw$, $cw$Procedures for guarding against, detecting, and reporting malicious software. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.308(a)(5)', 'HIPAA-164.308(a)(5)(ii)(C)', $cw$Log-in Monitoring (Addressable)$cw$, $cw$Procedures for monitoring log-in attempts and reporting discrepancies. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.308(a)(5)', 'HIPAA-164.308(a)(5)(ii)(D)', $cw$Password Management (Addressable)$cw$, $cw$Procedures for creating, changing, and safeguarding passwords. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.308(a)(6)', 'HIPAA-164.308(a)(6)(ii)', $cw$Response and Reporting (Required)$cw$, $cw$Identify and respond to suspected or known security incidents; mitigate, to the extent practicable, harmful effects of security incidents that are known to the covered entity or business associate; and document security incidents and their outcomes.$cw$, 'organizational', '1'),
      ('HIPAA-164.308(a)(7)', 'HIPAA-164.308(a)(7)(ii)(A)', $cw$Data Backup Plan (Required)$cw$, $cw$Establish and implement procedures to create and maintain retrievable exact copies of electronic protected health information.$cw$, 'technical', '1'),
      ('HIPAA-164.308(a)(7)', 'HIPAA-164.308(a)(7)(ii)(B)', $cw$Disaster Recovery Plan (Required)$cw$, $cw$Establish (and implement as needed) procedures to restore any loss of data.$cw$, 'organizational', '1'),
      ('HIPAA-164.308(a)(7)', 'HIPAA-164.308(a)(7)(ii)(C)', $cw$Emergency Mode Operation Plan (Required)$cw$, $cw$Establish (and implement as needed) procedures to enable continuation of critical business processes for protection of the security of electronic protected health information while operating in emergency mode.$cw$, 'organizational', '1'),
      ('HIPAA-164.308(a)(7)', 'HIPAA-164.308(a)(7)(ii)(D)', $cw$Testing and Revision Procedures (Addressable)$cw$, $cw$Implement procedures for periodic testing and revision of contingency plans. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'organizational', '2'),
      ('HIPAA-164.308(a)(7)', 'HIPAA-164.308(a)(7)(ii)(E)', $cw$Applications and Data Criticality Analysis (Addressable)$cw$, $cw$Assess the relative criticality of specific applications and data in support of other contingency plan components. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'strategic', '2'),
      ('HIPAA-164.308(b)(1)', 'HIPAA-164.308(b)(3)', $cw$Written Contract or Other Arrangement (Required)$cw$, $cw$Document the satisfactory assurances required by 164.308(b)(1) or (b)(2) through a written contract or other arrangement with the business associate that meets the applicable requirements of 164.314(a).$cw$, 'organizational', '1'),
      ('HIPAA-164.310(a)(1)', 'HIPAA-164.310(a)(2)(i)', $cw$Contingency Operations (Addressable)$cw$, $cw$Establish (and implement as needed) procedures that allow facility access in support of restoration of lost data under the disaster recovery plan and emergency mode operations plan in the event of an emergency. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'physical', '2'),
      ('HIPAA-164.310(a)(1)', 'HIPAA-164.310(a)(2)(ii)', $cw$Facility Security Plan (Addressable)$cw$, $cw$Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'physical', '2'),
      ('HIPAA-164.310(a)(1)', 'HIPAA-164.310(a)(2)(iii)', $cw$Access Control and Validation Procedures (Addressable)$cw$, $cw$Implement procedures to control and validate a person’s access to facilities based on their role or function, including visitor control, and control of access to software programs for testing and revision. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'physical', '2'),
      ('HIPAA-164.310(a)(1)', 'HIPAA-164.310(a)(2)(iv)', $cw$Maintenance Records (Addressable)$cw$, $cw$Implement policies and procedures to document repairs and modifications to the physical components of a facility which are related to security (for example, hardware, walls, doors, and locks). Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'physical', '2'),
      ('HIPAA-164.310(d)(1)', 'HIPAA-164.310(d)(2)(i)', $cw$Disposal (Required)$cw$, $cw$Implement policies and procedures to address the final disposition of electronic protected health information, and/or the hardware or electronic media on which it is stored.$cw$, 'physical', '1'),
      ('HIPAA-164.310(d)(1)', 'HIPAA-164.310(d)(2)(ii)', $cw$Media Re-use (Required)$cw$, $cw$Implement procedures for removal of electronic protected health information from electronic media before the media are made available for re-use.$cw$, 'physical', '1'),
      ('HIPAA-164.310(d)(1)', 'HIPAA-164.310(d)(2)(iii)', $cw$Accountability (Addressable)$cw$, $cw$Maintain a record of the movements of hardware and electronic media and any person responsible therefore. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'physical', '2'),
      ('HIPAA-164.310(d)(1)', 'HIPAA-164.310(d)(2)(iv)', $cw$Data Backup and Storage (Addressable)$cw$, $cw$Create a retrievable, exact copy of electronic protected health information, when needed, before movement of equipment. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.312(a)(1)', 'HIPAA-164.312(a)(2)(i)', $cw$Unique User Identification (Required)$cw$, $cw$Assign a unique name and/or number for identifying and tracking user identity.$cw$, 'technical', '1'),
      ('HIPAA-164.312(a)(1)', 'HIPAA-164.312(a)(2)(ii)', $cw$Emergency Access Procedure (Required)$cw$, $cw$Establish (and implement as needed) procedures for obtaining necessary electronic protected health information during an emergency.$cw$, 'technical', '1'),
      ('HIPAA-164.312(a)(1)', 'HIPAA-164.312(a)(2)(iii)', $cw$Automatic Logoff (Addressable)$cw$, $cw$Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.312(a)(1)', 'HIPAA-164.312(a)(2)(iv)', $cw$Encryption and Decryption (Addressable)$cw$, $cw$Implement a mechanism to encrypt and decrypt electronic protected health information. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.312(c)(1)', 'HIPAA-164.312(c)(2)', $cw$Mechanism to Authenticate Electronic Protected Health Information (Addressable)$cw$, $cw$Implement electronic mechanisms to corroborate that electronic protected health information has not been altered or destroyed in an unauthorized manner. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.312(e)(1)', 'HIPAA-164.312(e)(2)(i)', $cw$Integrity Controls (Addressable)$cw$, $cw$Implement security measures to ensure that electronically transmitted electronic protected health information is not improperly modified without detection until disposed of. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.312(e)(1)', 'HIPAA-164.312(e)(2)(ii)', $cw$Encryption (Addressable)$cw$, $cw$Implement a mechanism to encrypt electronic protected health information whenever deemed appropriate. Addressable (164.306(d)(3)): assess whether the specification is reasonable and appropriate; implement it, or document why it is not and implement an equivalent alternative measure if reasonable and appropriate.$cw$, 'technical', '2'),
      ('HIPAA-164.314(a)(1)', 'HIPAA-164.314(a)(2)(i)', $cw$Business Associate Contracts (Required)$cw$, $cw$The contract must provide that the business associate will comply with the applicable requirements of the Security Rule; ensure that any subcontractors that create, receive, maintain, or transmit electronic protected health information on its behalf agree to comply; and report to the covered entity any security incident of which it becomes aware, including breaches of unsecured protected health information as required by 164.410.$cw$, 'organizational', '1'),
      ('HIPAA-164.314(a)(1)', 'HIPAA-164.314(a)(2)(ii)', $cw$Other Arrangements (Required)$cw$, $cw$The covered entity is in compliance if it has another arrangement in place that meets the requirements of 164.504(e)(3) (for example, a memorandum of understanding when the covered entity and business associate are both governmental entities).$cw$, 'organizational', '1'),
      ('HIPAA-164.314(a)(1)', 'HIPAA-164.314(a)(2)(iii)', $cw$Business Associate Contracts with Subcontractors (Required)$cw$, $cw$The requirements of 164.314(a)(2)(i) and (ii) apply to the contract or other arrangement between a business associate and a subcontractor in the same manner as between a covered entity and business associate.$cw$, 'organizational', '1'),
      ('HIPAA-164.314(b)(1)', 'HIPAA-164.314(b)(2)', $cw$Group Health Plan Documents (Required)$cw$, $cw$The plan documents of the group health plan must be amended to require the plan sponsor to implement safeguards for electronic protected health information, ensure adequate separation, ensure agents agree to implement safeguards, and report security incidents to the group health plan.$cw$, 'organizational', '1')
    ) AS spec(parent_code, control_id, title, description, control_type, priority)
    JOIN framework_controls parent ON parent.framework_id = fw_id AND parent.control_id = spec.parent_code
  ON CONFLICT (framework_id, control_id) DO UPDATE
    SET title = EXCLUDED.title,
        description = EXCLUDED.description,
        parent_control_id = EXCLUDED.parent_control_id,
        is_enhancement = true;

  UPDATE frameworks
     SET description = 'HIPAA Security Rule (45 CFR Part 164 Subpart C): administrative, physical and technical safeguard standards with their Required and Addressable implementation specifications.' -- ip-hygiene:ignore (our description; 45 CFR is public domain)
   WHERE id = fw_id;
END$$;
